server:
  port: 8081
  servlet.context-path: /consumer-goods/v1


spring:
  application:
    name: customer-services
  datasource:
    url: jdbc:sqlserver://localhost:1433;databaseName=your_database_name;encrypt=true;trustServerCertificate=true;
    username: your_username
    password: your_password
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
