#name: Build and Push to ACR

#on:
  #workflow_run:
  #  workflows: [ "First Workflow" ]
  #  types:
   #   - completed


#jobs:
 # build-and-push:
   # runs-on: ubuntu-latest
    #steps:
      # 1. Check out the code
    #  - name: Checkout Repository
    #    uses: actions/checkout@v4

      # 2. Log in to Azure Container Registry
    #  - name: Log in to ACR
    #    uses: azure/docker-login@v2
    #    with:
     #     login-server: ${{ secrets.ACR_LOGIN_SERVER }}
     #     username: ${{ secrets.ACR_USERNAME }}
     #     password: ${{ secrets.ACR_PASSWORD }}

      # 3. Build and Push the image
    #  - name: Build and Push Docker Image
     #   run: |
     #     docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
     #     docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
