name: First Workflow

on:
 push:
  branches: [ "main" ]

jobs: 
  build:
    runs-on: ubuntu-latest
    
    steps:
      # 1. Check out the code
    - name: Checkout code
      uses: actions/checkout@v4

      # 2. Setup JDK
    - name: Setup Java JDK
      uses: actions/setup-java@v5.1.0
      with:
       java-version: 17
       distribution: 'temurin'
       cache: maven

      # 3. Build with Maven
    - name: Build with Maven
      run: mvn clean install --file pom.xml

      # 4. Upload a Build Artifact
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v6.0.0
      with:
       name: customer-services
       path: target/*.jar

      # 5. Log in to Azure Container Registry
    - name: Log in to ACR
      uses: azure/docker-login@v2
      with:
        login-server: ${{ secrets.ACR_LOGIN_SERVER }}
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
      run: |
        docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
      

      # 6. Build and Push the image
    #- name: Build and Push Docker Image
     # uses: docker/build-push-action@v6
     # with:
      #  context: .
      #  push: true
      #  tags: ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
     #   cache-from: type=gha
      #  cache-to: type=gha,mode=max
      #run: |
       # docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} -p ${{ secrets.ACR_PASSWORD }}
       # docker build . -t ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
       # docker push ${{ secrets.ACR_LOGIN_SERVER }}/customer-services:0.0.1-SNAPSHOT
     
          
